core/urls.py
from django.urls import path
from . import views as core_views

app_name = 'core'
urlpatterns = [
	path('', core_views.HomeView.as_view(), name='home-page'),
	
	path('order-summary/', core_views.OrderSummaryView.as_view(), name='order-summary'),
	path('checkout/', core_views.CheckoutView.as_view(), name='checkout'),
	path('add-coupon/', core_views.add_coupon, name='add-coupon'),
	path('remove-coupon/', core_views.remove_coupon, name='remove-coupon'),
	path('request-refund/', core_views.RefundView.as_view(), name='request-refund'),

	path('product/<pk>/', core_views.ProductDetailView.as_view(), name="product"),

	path('add-to-cart/<pk>/', core_views.add_to_cart, name="add-to-cart"),
	path('decrease-single-item/<pk>/', core_views.decrease_single_item_from_cart, name="decrease-from-cart"),
	path('remove-from-cart/<pk>/', core_views.remove_from_cart, name="remove-from-cart"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls' , namespace='core')),

    path('accounts/', include('allauth.urls')),
    


    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

from django.urls import reverse
from django_countries.fields import CountryField

from django.contrib.auth.models import User
# Create your models here.


CATEGORY_CHOICES = (
	("S","Shirt"),
	("SW","Sport Wear"),
	("OW","OutWear")
)

LABELCHOICES = (
	("P","primary"),
	("D","danger"),
	("S","secondary")
)
ADDRESS_CHOICES = (
	("B","billing"),
	("S","shipping")
)

class Item(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	price = models.IntegerField(default=120)
	price_after_disc = models.IntegerField(null=True, blank=True)
	category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
	label = models.CharField(choices=LABELCHOICES, max_length=1)
	

	def __str__(self):
		return f'{self.title}'

	def get_absolute_url(self):
		return reverse("core:product" , kwargs={'pk': self.id})

	def get_add_to_cart_url(self):
		return reverse("core:add-to-cart" , kwargs={'pk': self.id})

	def get_remove_from_cart_url(self):
		return reverse("core:remove-from-cart" , kwargs={'pk': self.id})




class OrderItem(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	ordered = models.BooleanField(default=False)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)

	def __str__(self):
		return f'{self.quantity} of {self.item.title}'

	def get_total_price(self):
		return self.item.price * self.quantity

	def get_total_price_after_disc(self):
		return self.quantity * self.item.price_after_disc

	def get_total_disc(self):
		return int(self.get_total_price - self.get_total_price_after_disc)

	def get_price(self):
		if self.item.price_after_disc:
			return self.get_total_price_after_disc()
		else:
			return self.get_total_price()

class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	ref_code = models.CharField(max_length=20, null=True, blank=True)
	items = models.ManyToManyField(OrderItem)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default=False)
	billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, null=True, blank=True)
	shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, null=True, blank=True)
	payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, null=True, blank=True)
	coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, null=True, blank=True)

	refund_requested = models.BooleanField(default=False)
	refund_accepted = models.BooleanField(default=False)

	def __str__(self):
		return f'{self.user.username} on {self.start_date}'


	def get_order_total_price(self):
		sum = 0
		for order_item in self.items.all():
			if order_item.item.price_after_disc:
				sum += order_item.get_total_price_after_disc()
			else:
				sum += order_item.get_total_price()
		if self.coupon:
			sum -= self.coupon.amount
		return sum

	def has_coupon(self):
		if self.coupon == None:
			return False
		return True


class Address(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	street_address = models.CharField(max_length=100)
	apartment_address = models.CharField(max_length=100)
	country = CountryField(multiple=False)
	zip = models.CharField(max_length=10)
	default = models.BooleanField(default=False)
	address_type = models.CharField(max_length=1, default="B", choices=ADDRESS_CHOICES)

	def __str__(self):
		return f'{self.user.username}'


class Payment(models.Model):
	stripe_charge_id = models.CharField(max_length=100)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	amount = models.FloatField()
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user.username}'


class Coupon(models.Model):
	coupon = models.CharField(max_length=20)
	amount = models.FloatField(default=0)


	def __str__(self):
		return f'{self.coupon}'


class Refund(models.Model):
	order_ref_code = models.CharField(max_length=20)
	description = models.TextField()
	request_date = models.DateTimeField(auto_now_add=True)
	closed = models.BooleanField(default=False)

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
		('S','Stripe'),
		('p','PayPal')
	)

class CheckoutForm(forms.Form):
	billing_address1 = forms.CharField(required=False ,widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder':"1234 Main St"
		}))
	billing_address2 = forms.CharField(required=False ,widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder':"Apartment or suite"
		}))
	billing_country = CountryField(blank=True,blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
		'class':'custom-select d-block w-100'
		}))
	billing_zip = forms.CharField(required=False ,widget=forms.TextInput(attrs={
		'class':'form-control',
		}))
	shipping_as_billing = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={
		'class':'form-check-input'
		}))
	set_default_billing = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={
		'class':'form-check-input'
		}))
	use_default_billing = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={
		'class':'form-check-input'
		}))
	# ===========================================================
	# ===========================================================
	shipping_address1 = forms.CharField(required=False ,widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder':"1234 Main St"
		}))
	shipping_address2 = forms.CharField(required=False ,widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder':"Apartment or suite"
		}))
	shipping_country = CountryField(blank=True,blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
		'class':'custom-select d-block w-100'
		}))
	shipping_zip = forms.CharField(required=False ,widget=forms.TextInput(attrs={
		'class':'form-control',
		}))
	set_default_shipping = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={
		'class':'form-check-input'
		}))
	use_default_shipping = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={
		'class':'form-check-input'
		}))

	# ============================================================
	payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class RefundForm(forms.Form):
	ref_code = forms.CharField(widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder':""
		}))
	description = forms.CharField(widget=forms.Textarea(attrs={
		'class':'form-control',
		}))

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.contrib import messages

from .forms import CheckoutForm, RefundForm
from .models import Item, OrderItem, Order, Address, Payment, Coupon, Refund

import string
import random
import stripe

# This is your test secret API key.
stripe.api_key = 'sk_test_51KFRKhA4DXRyfULlrSdK7tXMBkowVabtTbmUJtNYwOjLdtFv8LKxBAxKLvWoFjayqlAXcZoFlHi5fulb1A1D8NKa00B6y8odr9'


# Create your views here.

class HomeView(ListView):
	model = Item
	paginate_by = 1
	template_name = 'core/home-page.html'

class OrderSummaryView(View):
	def get(self, *args, **kwargs):
		try:
			order = get_object_or_404(Order, user=self.request.user, ordered=False)
		except:
			order = Order(user=self.request.user, ordered=False, ordered_date=timezone.now())
			order.save()
		print(order)
		context = {
			'order': order,
		}
		return render(self.request, "core/order_summary.html", context)

class ProductDetailView(DetailView):
	model = Item
	template_name = 'core/product.html'


class CheckoutView(View):
	def get(self, *args, **kwargs):
		try:
			order = Order.objects.get(user=self.request.user, ordered=False)
			form = CheckoutForm()
			context = {
				'form': form,
				'order':order
			}
			try:
				default_shipping = Address.objects.filter(user=self.request.user, default=True, address_type='S')[0]
				context.update({'shipping_address':default_shipping})
			except:
				pass
			try:
				default_billing = Address.objects.filter(user=self.request.user, default=True, address_type='B')[0]
				context.update({'billing_address':default_billing})
			except:
				pass
			print(context)
			return render(self.request, 'core/checkout.html', context)
		except Exception as e:
			print(e)
			# TODO: redirect with error message
			messages.info(self.request, "NO ACTIVE ORDERs")
			return redirect("core:home-page")
	def post(self, *args, **kwargs):

		shipping_as_billing = self.request.POST.get('shipping_as_billing')
		set_default_billing = self.request.POST.get('set_default_billing')
		use_default_billing = self.request.POST.get('use_default_billing')

		set_default_shipping = self.request.POST.get('set_default_shipping')
		use_default_shipping = self.request.POST.get('use_default_shipping')

		form = CheckoutForm(self.request.POST or None)
		try:
			order = Order.objects.get(user=self.request.user, ordered=False)
			if form.is_valid():
				print(form.cleaned_data)
				print("#####THIS FORM IS VALID#####")
				user = self.request.user

				if use_default_billing:
					try:
						billing_address = Address.objects.get(user=user, default=True, address_type="B")
					except:
						messages.error(self.request, "you have no default billing address")
						return redirect('core:checkout')
				else:
					billing_address1 = self.request.POST.get('billing_address1')
					billing_address2 = self.request.POST.get('billing_address2')
					billing_country = self.request.POST.get('billing_country')
					billing_zip = self.request.POST.get('billing_zip')
					billing_address = Address(
							user = user,
							street_address=billing_address1,
							apartment_address=billing_address2,
							country=billing_country,
							zip=billing_zip,
							address_type="B"
						)
					if set_default_billing:
						billing_address.default = True
					billing_address.save()
					if shipping_as_billing:
						shipping_address = billing_address
						shipping_address.id = None
						shipping_address.address_type = "S"
						shipping_address.save()

				if not shipping_as_billing:
					if use_default_shipping:
						try:
							shipping_address = Address.objects.get(user=user, default=True, address_type="B")
						except:
							messages.error(self.request, "you have no default shipping address")
							return redirect('core:checkout')
					else:
						shipping_address1 = self.request.POST.get('shipping_address1')
						shipping_address2 = self.request.POST.get('shipping_address2')
						shipping_country = self.request.POST.get('shipping_country')
						shipping_zip = self.request.POST.get('shipping_zip')
						shipping_address = Address(
								user = user,
								street_address=shipping_address1,
								apartment_address=shipping_address2,
								country=shipping_country,
								zip=shipping_zip,
								address_type="S"
							)
						if set_default_shipping:
							shipping_address.default = True
						shipping_address.save()


				order.billing_address = billing_address
				order.shipping_address = shipping_address
				order.save()
				payment_option = self.request.POST.get("payment_option")
				'''will be included when paypal works
				if payment_option == "S":
					return redirect('core:payment' , payment_option="Stripe")
				elif payment_option == "P":
					return redirect('core:payment' , payment_option="Paypal")
				else:
					messages.info(self.request, "SELECT A CORRECT PAYMENT-OPTION...")
					return redirect('core:checkout')
				'''
				YOUR_DOMAIN = "http://127.0.0.1:8000/"
				try:
					checkout_session = stripe.checkout.Session.create(
					    line_items=[
							{
								# Provide the exact Price ID (for example, pr_1234) of the product you want to sell
								'price_data': {
									'currency':'usd',
									'product_data': {
										'name':'test100',
										'description':'test100 description'
									},
									'unit_amount':5000
								},
								'quantity': 1,
							},
						],
						mode='payment',
						success_url=YOUR_DOMAIN + 'success/',
						cancel_url=YOUR_DOMAIN + 'cancel/',
					)

					# TODO: edite the total amount in payment
					payment = Payment()
					payment.stripe_charge_id = checkout_session.id
					payment.user = self.request.user
					payment.amount = 10.5
					payment.save()

					# adding the payment into the order and set the order state to ordered
					# TODO: handle the stripe webhook
					# order.ordered = True
					# order.ref_code = random.randint(???)
					order.payment = payment
					order.save()

					# setting the order_items state to ordered
					order_items = order.items.all()
					order_items.bulk_update(ordered=True)


				except Exception as e:
					print(e)

				return redirect(checkout_session.url, code=303)
				print("##################################")
		except Exception as e:
			print(e)
			messages.info(self.request, "THERE IS NO ACTIVE ORDER")
			return redirect("core:order-summary")

		messages.info(self.request, "THERE IS A PROBLEM....")
		return redirect('core:checkout')


class RefundView(View):
	def get(self, *args, **kwargs):
		form = RefundForm()
		context = {
			'form': form
		}
		return render(self.request, "core/refund_request.html", context)

	def post(self, *args, **kwargs):
		ref_code = self.request.POST.get("ref_code")
		description = self.request.POST.get("description")
		try:
			order = Order.objects.get(user=self.request.user, ref_code=ref_code , ordered=True)
			order.refund_requested = True
			order.save()
			refund = Refund(order_ref_code=ref_code, description=description)
			refund.save()
			messages.success(self.request, f"your request have submited successfully")
			return redirect('core:request-refund')
		except:
			messages.error(self.request, f"You have no order with this ref_code {ref_code}")
			return redirect('core:request-refund')

def add_coupon(request):
	try:
		order = Order.objects.get(user=request.user, ordered=False)
		coupon_entered = request.POST.get('coupon')
		print(coupon_entered)
		coupon = Coupon.objects.get(coupon=coupon_entered)
		order.coupon = coupon
		order.save()
		return redirect("core:checkout")
	except Exception as e:
		print(e)
		messages.info(request, "INVALID")
		return redirect("core:checkout")

def remove_coupon(request):
	order = Order.objects.get(user=request.user, ordered=False)
	order.coupon = None
	order.save()
	return redirect("core:checkout")


def add_to_cart(request, pk):
	redirect_to = request.GET.get('redirect_to', 'core:product')
	item = get_object_or_404(Item, id=pk)
	order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		if order.items.filter(item__id=pk).exists():
			order_item.quantity += 1
			order_item.save()
			messages.info(request, 'the item increased successfuly.')
		else:
			order.items.add(order_item)
			messages.info(request, 'the item Added successfuly.')
	else:
		order = Order.objects.create(user=request.user, ordered_date=timezone.now())
		order.items.add(order_item)
		messages.info(request, 'Start new Order and Add the item successfuly.')

	if redirect_to == "core:product":
		return redirect(redirect_to, pk=pk)
	else:
		return redirect(redirect_to)


def remove_from_cart(request, pk):
	redirect_to = request.GET.get('redirect_to', 'core:product')
	item = get_object_or_404(Item, id=pk)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		if order.items.filter(item__id=pk).exists():
			order_item = OrderItem.objects.get(item=item, user=request.user, ordered=False)
			order.items.remove(order_item)
			order_item.delete()
			# message says: the item removed successfuly
			messages.info(request, 'the item removed successfuly.')
			if redirect_to == "core:product":
				return redirect(redirect_to, pk=pk)
			else:
				return redirect(redirect_to)
		else:
			# message says: the item isn't in your cart
			messages.info(request, "the item isn't in your cart.")
			if redirect_to == "core:product":
				return redirect(redirect_to, pk=pk)
			else:
				return redirect(redirect_to)
	else:
		# return error message says: There are no active Order
		messages.info(request, 'There are no active Order.')
		if redirect_to == "core:product":
			return redirect(redirect_to, pk=pk)
		else:
			return redirect(redirect_to)


def decrease_single_item_from_cart(request, pk):

core/templates/core/base.html
{% load static %}

  
  {% include "core/header.html" %}

  

  {% block content %}{% endblock %}

  {% include "core/footer.html" %}

  {% block extra_script %}{% endblock extra_script %}
  <!-- SCRIPTS -->
  <!-- JQuery -->
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

core/templates/core/cancel.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

core/templates/core/cart_snippet.html
<!-- Heading -->

<h4 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted">Your cart</span>
  <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
</h4>

<!-- Cart -->
<ul id="cart-snippet" class="list-group mb-1 z-depth-1" style="max-height: 250px; overflow: auto;">
  {% for order_item in order.items.all %}
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
      <small class="text-muted">{{order_item.item.description|slice:60}}</small>
    </div>
    <span class="text-muted">${{order_item.get_price}}</span>
  </li>
  {% endfor %}
  
</ul>
<ul class="list-group mb-3 z-depth-1">
  <li class="list-group-item d-flex justify-content-between bg-light">
    <div class="text-success">
      <h6 class="my-0">Promo code</h6>
      <small>{{order.coupon.coupon}}</small>
    </div>
    <span class="text-success">-${{order.coupon.amount}}</span>
  </li>
  <li class="list-group-item d-flex justify-content-between">
    <span>Total (USD)</span>
    <strong>${{order.get_order_total_price}}</strong>
  </li>
</ul>
<!-- Cart -->

<!-- Promo code -->
{% if order.has_coupon %}
<form action="{% url 'core:remove-coupon' %}" class="card p-2" method="POST">
  {% csrf_token %}
  <div class="input-group float-right">
    <div class="input-group-append">
      <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Remove Coupon</button>
    </div>
  </div>
</form>
{% else %}
<form action="{% url 'core:add-coupon' %}" class="card p-2" method="POST">
  {% csrf_token %}
  <div class="input-group">
    <input name="coupon" type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
    <div class="input-group-append">
      <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
    </div>
  </div>
</form>

{% endif %}
<!-- Promo code -->

core/templates/core/home-page.html
{% extends 'core/base.html' %}

{% block content %}
  <!-- Insert carousel -->
  {% include "core/carousel.html" %}

  <!--Main layout-->
  <main>
    <div class="container mt-5">
      <!-- Insert navbar -->
      {% include "core/navbar.html" %}

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt="">
                <a href="{% url 'core:product' item.id %}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  {% if item.price_after_disc %}
                  <strong>${{ item.price_after_disc }}</strong>
                  {% else %}
                  <strong>${{ item.price }}</strong>
                  {% endif %}
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>
        <!--Grid row-->


      </section>
      <!--Section: Products v.3-->


      {% if is_paginated %}
      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}


          <li class="page-item active">
            <a class="page-link" href="">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <!--
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>
          -->

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>
  <!--Main layout-->

  {% endblock %}

core/templates/core/home.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Home</title>
</head>
<body>
	<h1>Home Paga With All Items For Test</h1>

	{% for item in items %}
		<div>{{ item }}</div>
	{% endfor %}
</body>
</html>

core/templates/core/order_summary.html
{% extends 'core/base.html' %}

{% block content %}

  <!--Main layout-->
  <main class="pt-5">
    <div class="container mt-5">
      <h2>Order Summary</h2>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item Title</th>
            <th scope="col">Price</th>
            <th scope="col">Discount</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in order.items.all %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{order_item.item.title}}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
              {% if order_item.item.price_after_disc %}
                  {{order_item.item.price_after_disc}}
              {% else %}
                -
              {% endif %}
            </td>
            <td>
              <a href="{% url 'core:decrease-from-cart' order_item.item.id %}" class="mr-2"><i class="fas fa-minus"></i></a>
                {{ order_item.quantity }}
              <a href="{% url 'core:add-to-cart' order_item.item.id %}?redirect_to=core:order-summary" class="ml-2"><i class="fas fa-plus"></i></a>
            </td>
            <td>
              {% if order_item.item.price_after_disc %}
                {{ order_item.get_total_price_after_disc }}
              {% else %}
                {{ order_item.get_total_price }}
              {% endif %}

              <a href="{% url 'core:remove-from-cart' order_item.item.id %}?redirect_to=core:order-summary">
                  <i class="fas fa-trash float-right" style="color:red;"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">Your Cart Is Empty</td>
            <td><a href="{% url 'core:home-page' %}" class="btn btn-info">Continue Shopping</a></td>
          </tr>
          {% endfor %}
          {% if order.get_order_total_price %}
            {% if order.has_coupon %}
              <tr>
                <td colspan="5"><b>Coupon</b></td>
                <td><b>-${{ order.coupon.amount }}</b></td>
              </tr>  
            {% endif %}
            <tr>
              <td colspan="5"><b>Total Price</b></td>
              <td><b>{{ order.get_order_total_price }}</b></td>
            </tr>
            <tr>
              <td colspan="6">
                <a href="{% url 'core:checkout' %}" class="float-right mr-5 btn btn-warning">ChechOut</a>
                <a href="{% url 'core:home-page' %}" class="float-right mr-5 btn btn-info">Continue Shopping</a>
              </td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </main>
  <!--Main layout-->

{% endblock %}

core/templates/core/payment.html
{% extends 'core/base.html' %}

{% block content %}
  
<h2>Payment</h2>

{% endblock %}

core/templates/core/refund_request.html
{% extends 'core/base.html' %}

{% block content %}
  
  	<main class="mt-5 pt-4 pb-5">
  		<div class="container">
  			<h2>Request Refund</h2>
  			<form method="POST">
  				{% csrf_token %}
  				{{form}}
  				<button class="btn btn-primary float-right" type="submit">Submit</button>
  			</form>
  		</div>
	</main>
{% endblock %}

core/templates/core/success.html
<!DOCTYPE html>
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>
      We appreciate your business! If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
  </section>
</body>
</html>